import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import * as fs from 'fs';

async function bootstrap() {
  // Load the certificates generated by your Dockerfile
  const httpsOptions = {
    key: fs.readFileSync('./secrets/privkey.pem'),
    cert: fs.readFileSync('./secrets/cert.pem'),
  };

  // Create the app with HTTPS options
  const app = await NestFactory.create(AppModule, {
    httpsOptions,
  });

  // Listen on port 443 to match the Gateway's expectations
  await app.listen(443);
}
bootstrap();