import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import * as fs from 'fs';

async function bootstrap() {
  // SSL keys are generated by the Dockerfile and placed in /app/secrets
  const httpsOptions = {
    key: fs.readFileSync('./secrets/privkey.pem'),
    cert: fs.readFileSync('./secrets/cert.pem'),
  };

  const app = await NestFactory.create(AppModule, { httpsOptions });

  // Essential for cleaning up DB connections when the container stops
  app.enableShutdownHooks();

  await app.listen(443);
  console.log('🚀 Auth Service secure on https://localhost:443');
}
bootstrap();