server {
    listen 443 ssl;
    server_name localhost;

    # Gateway SSL Certificates
    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    # # 1. Frontend (React) - Internal HTTP is usually fine for static files
    # location / {
    #     proxy_pass http://frontend:80;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }

    # --- WE have replaced the above ngnix server config in frontend container with the belowed redirecting to frontend-dev for hot relading (HMR)
    location / {
    # Point to the dev service and the port Vite uses
    proxy_pass http://frontend-dev:5173; 
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}

# Auth Service Logic (NestJS Microservice)
    location /api/auth/ {
    proxy_pass https://auth:443;    

    proxy_ssl_verify off; 
    
    # 4. Standard proxy headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location /api/boards/ {

    proxy_pass https://boards:443/boards/;
    proxy_ssl_verify off; 

    # 4. Standard proxy headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location /api/dashboard/ {

    proxy_pass https://dashboard:443/dashboard/;
    proxy_ssl_verify off; 

    # 4. Standard proxy headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location /api/chat/ {

    proxy_pass https://chat:443/chat/;
    proxy_ssl_verify off; 

    # 4. Standard proxy headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

}
